import { createFileRoute, Link } from "@tanstack/react-router";
import { Bell, CalendarDays, ChevronDown, Eye, Grid2X2, Heart, Home, List, Pencil, Plus, Search, Settings, Shirt, Signal, Trash2, Trophy, Users, X } from "lucide-react";
import { useMemo, useState } from "react";
import type React from "react";
import { emptyPlayer, flattenPlayers, getStoredPlayerSections, groupPlayers, normalizePlayerSections, persistPlayerSections, photoForPosition, playerPositions, type Player, type PlayerSection } from "../data/players";
import { UskLogo } from "../components/UskLogo";
import "../usk.css";

export const Route = createFileRoute("/admin/effectif")({ component: AdminEffectifPage, head: () => ({ meta: [{ title: "Effectif — Administration USK" }] }) });
const filters = ["Tous", "Gardiens", "Défenseurs", "Milieux", "Attaquants"];
type Staff = { id: string; name: string; role: string; photo: string };
const staffSeed: Staff[] = [
  { id: "president", name: "M. Nabil Ben Youssef", role: "Président du club", photo: "" },
  { id: "coach", name: "Sofien Trabelsi", role: "Entraîneur principal", photo: "" },
  { id: "assistant", name: "Karim Derbali", role: "Adjoint", photo: "" },
  { id: "physical", name: "Amine Labidi", role: "Préparateur physique", photo: "" },
  { id: "physio", name: "Walid Saidi", role: "Kinésithérapeute", photo: "" },
];
const STAFF_KEY = "usk-staff-v1";
function readStaff(): Staff[] { try { const value = localStorage.getItem(STAFF_KEY); return value ? JSON.parse(value) : staffSeed; } catch { return staffSeed; } }
function fallbackPhoto(position: string) { return photoForPosition(position); }

export function AdminEffectifPage() {
  const [sections, setSections] = useState<PlayerSection[]>(() => normalizePlayerSections(getStoredPlayerSections()));
  const [staff, setStaff] = useState<Staff[]>(() => readStaff());
  const [editingPlayer, setEditingPlayer] = useState<Player | null>(null);
  const [viewingPlayer, setViewingPlayer] = useState<Player | null>(null);
  const [editingStaff, setEditingStaff] = useState<Staff | null>(null);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Tous"); const [view, setView] = useState<"grid" | "list">("grid");
  const allPlayers = flattenPlayers(sections);
  const players = useMemo(() => allPlayers.filter((p) => {
    const matchesQuery = `${p.name} ${p.position}`.toLowerCase().includes(query.toLowerCase());
    const matchesFilter = filter === "Tous" || (filter === "Gardiens" ? p.position.includes("Gardien") : filter === "Défenseurs" ? /Défenseur|Latéral/.test(p.position) : filter === "Milieux" ? p.position.includes("Milieu") : /Ailier|Avant/.test(p.position));
    return matchesQuery && matchesFilter;
  }), [allPlayers, query, filter]);
  const commitPlayers = (next: Player[]) => { const grouped = groupPlayers(next); setSections(grouped); persistPlayerSections(grouped); };
  const savePlayer = (p: Player) => { commitPlayers([...allPlayers.filter((x) => x.id !== p.id), p]); setEditingPlayer(null); };
  const saveStaff = (item: Staff) => { const next = [...staff.filter((x) => x.id !== item.id), item]; setStaff(next); localStorage.setItem(STAFF_KEY, JSON.stringify(next)); setEditingStaff(null); };
  const remove = (id: string, type: "player" | "staff") => { if (!window.confirm("Supprimer cet élément ?")) return; if (type === "player") commitPlayers(allPlayers.filter((p) => p.id !== id)); else { const next = staff.filter((x) => x.id !== id); setStaff(next); localStorage.setItem(STAFF_KEY, JSON.stringify(next)); } };
  return <div className="effectif-shell">
    <aside className="effectif-sidebar"><div className="effectif-brand"><UskLogo /><div><strong>USK</strong><span>UNION SPORTIVE<br />DE KELIBIA</span></div></div><nav>{[[Home,"Accueil","/admin"],[Users,"Effectif","/admin/effectif"],[Users,"Équipes","/admin/equipes"],[Shirt,"Tenues","/admin/tenues"],[CalendarDays,"Matchs","/admin/matchs"],[Signal,"Live match","/admin/live-match"],[Trophy,"Classement","/admin/classement"],[Settings,"Paramètres","/admin"]].map(([Icon, label, href]) => <Link key={String(label)} to={href as string} className={label === "Effectif" ? "active" : ""}><Icon /><span>{label}</span></Link>)}</nav><div className="effectif-sidebar-promo">Kelibia<br /><b>Toujours<br />Plus Haut</b></div></aside>
    <main className="effectif-content"><header className="effectif-topbar"><label><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher un joueur, un poste..." /></label><div className="effectif-account"><Bell /><b>3</b><span className="account-avatar">A</span><strong>Admin</strong><ChevronDown /></div></header>
      <div className="effectif-body"><div className="effectif-breadcrumb">Accueil <b>›</b> Effectif</div><section className="effectif-hero"><div><h1><Users /> Effectif</h1><p>Saison 2026 / 2027 · {allPlayers.length + staff.length} membres</p></div><div className="hero-copy">Plus qu&apos;un club<br /><b>Une famille</b></div></section>
      <section className="staff-section"><h2><span>♛</span> Staff &amp; Direction <small>({staff.length})</small></h2><div className="staff-grid">{staff.map((item) => <article className="staff-card" key={item.id}><button className="favorite"><Heart /></button><div className="staff-photo">{item.photo ? <img src={item.photo} alt={item.name} /> : <Users />}</div><strong>{item.name}</strong><span>{item.role}</span><div className="card-actions"><button onClick={() => setEditingStaff(item)} aria-label="Voir"><Eye /></button><button onClick={() => setEditingStaff(item)} aria-label="Modifier"><Pencil /></button><button onClick={() => remove(item.id, "staff")} aria-label="Supprimer"><Trash2 /></button></div></article>)}<button className="add-staff" onClick={() => setEditingStaff({ id: crypto.randomUUID(), name: "", role: "Membre du staff", photo: "" })}><Plus /><span>Ajouter membre</span></button></div></section>
      <div className="roster-toolbar"><div className="roster-tabs">{filters.map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item} <small>{item === "Tous" ? allPlayers.length : players.filter((p) => item === "Gardiens" ? p.position.includes("Gardien") : item === "Défenseurs" ? /Défenseur|Latéral/.test(p.position) : item === "Milieux" ? p.position.includes("Milieu") : /Ailier|Avant/.test(p.position)).length}</small></button>)}</div><div className="roster-tools"><button className="sort-button">⇵ Âge (croissant) <ChevronDown /></button><button className={view === "grid" ? "selected" : ""} onClick={() => setView("grid")}><Grid2X2 /></button><button className={view === "list" ? "selected" : ""} onClick={() => setView("list")}><List /></button><button className="add-button" onClick={() => setEditingPlayer(emptyPlayer())}><Plus /> Ajouter</button></div></div>
      <div className={view === "grid" ? "player-grid" : "player-list"}>{players.map((player) => <article className="player-card" key={player.id}><div className="player-number">{player.num}</div><button className="favorite"><Heart /></button><img src={player.photo || fallbackPhoto(player.position)} alt={player.name} /><strong>{player.name}</strong><span className="position-pill">{player.position}</span><div className="player-meta">◷ {player.age} ans <i>●</i> Tunisie</div><div className="card-actions"><button onClick={() => setViewingPlayer(player)} aria-label="Voir"><Eye /></button><button onClick={() => setEditingPlayer(player)} aria-label="Modifier"><Pencil /></button><button onClick={() => remove(player.id, "player")}><Trash2 /></button></div></article>)}</div>
      </div></main>{viewingPlayer && <PlayerDetails player={viewingPlayer} onClose={() => setViewingPlayer(null)} />}{editingPlayer && <PlayerEditor player={editingPlayer} onSave={savePlayer} onClose={() => setEditingPlayer(null)} />}{editingStaff && <StaffEditor staff={editingStaff} onSave={saveStaff} onClose={() => setEditingStaff(null)} />}
  </div>;
}
function PlayerDetails({ player, onClose }: { player: Player; onClose: () => void }) { return <div className="modal-backdrop"><section className="player-detail-modal"><button className="detail-close" onClick={onClose} aria-label="Fermer"><X /></button><img src={player.photo || fallbackPhoto(player.position)} alt={player.name} /><div className="player-detail-copy"><small>PROFIL JOUEUR · USK</small><h2>{player.name}</h2><span className="position-pill">{player.position}</span><div className="detail-facts"><b><em>#{player.num}</em> Numéro</b><b><em>{player.age}</em> ans</b><b><em>{player.height || "—"}</em> Taille</b><b><em>{player.foot || "—"}</em> Pied</b></div><div className="detail-stats"><b>{player.stats.matches}<small>Matchs</small></b><b>{player.stats.goals}<small>Buts</small></b><b>{player.stats.assists}<small>Passes</small></b><b>{player.stats.yellow}<small>Jaunes</small></b></div></div></section></div> }
function PlayerEditor({ player, onSave, onClose }: { player: Player; onSave: (p: Player) => void; onClose: () => void }) { const [draft, setDraft] = useState(player); const [preview, setPreview] = useState(player.photo); const update = (key: keyof Player, value: string | number) => setDraft((p) => ({ ...p, [key]: value })); return <Modal title={player.name ? "Modifier le joueur" : "Ajouter un joueur"} onClose={onClose}><form onSubmit={(e) => { e.preventDefault(); if (draft.name.trim()) onSave({ ...draft, name: draft.name.trim(), photo: preview || fallbackPhoto(draft.position) }); }}><div className="upload-photo"><img src={preview || fallbackPhoto(draft.position)} alt="Aperçu" /><label>Importer une photo<input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) { const reader = new FileReader(); reader.onload = () => setPreview(String(reader.result)); reader.readAsDataURL(file); } }} /></label></div><div className="form-grid"><Field label="Nom complet"><input required value={draft.name} onChange={(e) => update("name", e.target.value)} /></Field><Field label="Numéro"><input type="number" min="1" max="99" value={draft.num} onChange={(e) => update("num", Number(e.target.value))} /></Field><Field label="Poste"><select value={draft.position} onChange={(e) => update("position", e.target.value)}>{playerPositions.map((p) => <option key={p}>{p}</option>)}</select></Field><Field label="Âge"><input type="number" min="15" max="45" value={draft.age} onChange={(e) => update("age", Number(e.target.value))} /></Field></div><ModalFooter onClose={onClose} label="Enregistrer le joueur" /></form></Modal> }
function StaffEditor({ staff, onSave, onClose }: { staff: Staff; onSave: (s: Staff) => void; onClose: () => void }) { const [draft, setDraft] = useState(staff); return <Modal title={staff.name ? "Modifier le membre" : "Ajouter un membre"} onClose={onClose}><form onSubmit={(e) => { e.preventDefault(); if (draft.name.trim()) onSave({ ...draft, name: draft.name.trim() }); }}><div className="upload-photo"><img src={draft.photo || "/usk-official-background.png"} alt="Portrait du membre" /><label>Importer une photo professionnelle<input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) { const reader = new FileReader(); reader.onload = () => setDraft({ ...draft, photo: String(reader.result) }); reader.readAsDataURL(file); } }} /></label></div><div className="form-grid"><Field label="Nom complet"><input required value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></Field><Field label="Fonction"><input required value={draft.role} onChange={(e) => setDraft({ ...draft, role: e.target.value })} /></Field></div><ModalFooter onClose={onClose} label="Enregistrer" /></form></Modal> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field">{label}{children}</label> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop"><section className="modal"><header><div><small>ADMINISTRATION USK</small><h2>{title}</h2></div><button onClick={onClose} aria-label="Fermer"><X /></button></header>{children}</section></div> }
function ModalFooter({ onClose, label }: { onClose: () => void; label: string }) { return <footer className="modal-footer"><button type="button" onClick={onClose}>Annuler</button><button className="add-button" type="submit">{label}</button></footer> }
export default AdminEffectifPage;
