/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as EffectifRouteImport } from './routes/effectif'
import { Route as LiveMatchRouteImport } from './routes/live-match'
import { Route as MatchCenterRouteImport } from './routes/match-center'
import { Route as MatchsRouteImport } from './routes/matchs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as TenuesRouteImport } from './routes/tenues'
import { Route as AdminClassementRouteImport } from './routes/admin.classement'
import { Route as AdminEffectifRouteImport } from './routes/admin.effectif'
import { Route as AdminEquipesRouteImport } from './routes/admin.equipes'
import { Route as AdminLiveMatchRouteImport } from './routes/admin.live-match'
import { Route as AdminMatchsRouteImport } from './routes/admin.matchs'
import { Route as AdminTenuesRouteImport } from './routes/admin.tenues'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectifRoute = EffectifRouteImport.update({
  id: '/effectif',
  path: '/effectif',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMatchRoute = LiveMatchRouteImport.update({
  id: '/live-match',
  path: '/live-match',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchCenterRoute = MatchCenterRouteImport.update({
  id: '/match-center',
  path: '/match-center',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchsRoute = MatchsRouteImport.update({
  id: '/matchs',
  path: '/matchs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const TenuesRoute = TenuesRouteImport.update({
  id: '/tenues',
  path: '/tenues',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassementRoute = AdminClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEffectifRoute = AdminEffectifRouteImport.update({
  id: '/effectif',
  path: '/effectif',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipesRoute = AdminEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveMatchRoute = AdminLiveMatchRouteImport.update({
  id: '/live-match',
  path: '/live-match',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchsRoute = AdminMatchsRouteImport.update({
  id: '/matchs',
  path: '/matchs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenuesRoute = AdminTenuesRouteImport.update({
  id: '/tenues',
  path: '/tenues',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classement': typeof ClassementRoute
  '/effectif': typeof EffectifRoute
  '/live-match': typeof LiveMatchRoute
  '/match-center': typeof MatchCenterRoute
  '/matchs': typeof MatchsRoute
  '/news': typeof NewsRoute
  '/plus': typeof PlusRoute
  '/tenues': typeof TenuesRoute
  '/admin/classement': typeof AdminClassementRoute
  '/admin/effectif': typeof AdminEffectifRoute
  '/admin/equipes': typeof AdminEquipesRoute
  '/admin/live-match': typeof AdminLiveMatchRoute
  '/admin/matchs': typeof AdminMatchsRoute
  '/admin/tenues': typeof AdminTenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classement': typeof ClassementRoute
  '/effectif': typeof EffectifRoute
  '/live-match': typeof LiveMatchRoute
  '/match-center': typeof MatchCenterRoute
  '/matchs': typeof MatchsRoute
  '/news': typeof NewsRoute
  '/plus': typeof PlusRoute
  '/tenues': typeof TenuesRoute
  '/admin/classement': typeof AdminClassementRoute
  '/admin/effectif': typeof AdminEffectifRoute
  '/admin/equipes': typeof AdminEquipesRoute
  '/admin/live-match': typeof AdminLiveMatchRoute
  '/admin/matchs': typeof AdminMatchsRoute
  '/admin/tenues': typeof AdminTenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/classement': typeof ClassementRoute
  '/effectif': typeof EffectifRoute
  '/live-match': typeof LiveMatchRoute
  '/match-center': typeof MatchCenterRoute
  '/matchs': typeof MatchsRoute
  '/news': typeof NewsRoute
  '/plus': typeof PlusRoute
  '/tenues': typeof TenuesRoute
  '/admin/classement': typeof AdminClassementRoute
  '/admin/effectif': typeof AdminEffectifRoute
  '/admin/equipes': typeof AdminEquipesRoute
  '/admin/live-match': typeof AdminLiveMatchRoute
  '/admin/matchs': typeof AdminMatchsRoute
  '/admin/tenues': typeof AdminTenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/classement'
    | '/effectif'
    | '/live-match'
    | '/match-center'
    | '/matchs'
    | '/news'
    | '/plus'
    | '/tenues'
    | '/admin/classement'
    | '/admin/effectif'
    | '/admin/equipes'
    | '/admin/live-match'
    | '/admin/matchs'
    | '/admin/tenues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/classement'
    | '/effectif'
    | '/live-match'
    | '/match-center'
    | '/matchs'
    | '/news'
    | '/plus'
    | '/tenues'
    | '/admin/classement'
    | '/admin/effectif'
    | '/admin/equipes'
    | '/admin/live-match'
    | '/admin/matchs'
    | '/admin/tenues'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/classement'
    | '/effectif'
    | '/live-match'
    | '/match-center'
    | '/matchs'
    | '/news'
    | '/plus'
    | '/tenues'
    | '/admin/classement'
    | '/admin/effectif'
    | '/admin/equipes'
    | '/admin/live-match'
    | '/admin/matchs'
    | '/admin/tenues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClassementRoute: typeof ClassementRoute
  EffectifRoute: typeof EffectifRoute
  LiveMatchRoute: typeof LiveMatchRoute
  MatchCenterRoute: typeof MatchCenterRoute
  MatchsRoute: typeof MatchsRoute
  NewsRoute: typeof NewsRoute
  PlusRoute: typeof PlusRoute
  TenuesRoute: typeof TenuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effectif': {
      id: '/effectif'
      path: '/effectif'
      fullPath: '/effectif'
      preLoaderRoute: typeof EffectifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-match': {
      id: '/live-match'
      path: '/live-match'
      fullPath: '/live-match'
      preLoaderRoute: typeof LiveMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-center': {
      id: '/match-center'
      path: '/match-center'
      fullPath: '/match-center'
      preLoaderRoute: typeof MatchCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchs': {
      id: '/matchs'
      path: '/matchs'
      fullPath: '/matchs'
      preLoaderRoute: typeof MatchsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenues': {
      id: '/tenues'
      path: '/tenues'
      fullPath: '/tenues'
      preLoaderRoute: typeof TenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classement': {
      id: '/admin/classement'
      path: '/classement'
      fullPath: '/admin/classement'
      preLoaderRoute: typeof AdminClassementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/effectif': {
      id: '/admin/effectif'
      path: '/effectif'
      fullPath: '/admin/effectif'
      preLoaderRoute: typeof AdminEffectifRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipes': {
      id: '/admin/equipes'
      path: '/equipes'
      fullPath: '/admin/equipes'
      preLoaderRoute: typeof AdminEquipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-match': {
      id: '/admin/live-match'
      path: '/live-match'
      fullPath: '/admin/live-match'
      preLoaderRoute: typeof AdminLiveMatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matchs': {
      id: '/admin/matchs'
      path: '/matchs'
      fullPath: '/admin/matchs'
      preLoaderRoute: typeof AdminMatchsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenues': {
      id: '/admin/tenues'
      path: '/tenues'
      fullPath: '/admin/tenues'
      preLoaderRoute: typeof AdminTenuesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClassementRoute: typeof AdminClassementRoute
  AdminEffectifRoute: typeof AdminEffectifRoute
  AdminEquipesRoute: typeof AdminEquipesRoute
  AdminLiveMatchRoute: typeof AdminLiveMatchRoute
  AdminMatchsRoute: typeof AdminMatchsRoute
  AdminTenuesRoute: typeof AdminTenuesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassementRoute: AdminClassementRoute,
  AdminEffectifRoute: AdminEffectifRoute,
  AdminEquipesRoute: AdminEquipesRoute,
  AdminLiveMatchRoute: AdminLiveMatchRoute,
  AdminMatchsRoute: AdminMatchsRoute,
  AdminTenuesRoute: AdminTenuesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClassementRoute: ClassementRoute,
  EffectifRoute: EffectifRoute,
  LiveMatchRoute: LiveMatchRoute,
  MatchCenterRoute: MatchCenterRoute,
  MatchsRoute: MatchsRoute,
  NewsRoute: NewsRoute,
  PlusRoute: PlusRoute,
  TenuesRoute: TenuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
